global:
  scrape_interval: 5s # Set to 5s for more responsive metrics in this research project
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'etl-stream'
    static_configs:
      - targets: ['host.docker.internal:9000']
